### ISSUE TITLE
Vite configuration might cause occasional failures in build

### ISSUE THREAD

**Issue by madsnedergaard** [wtchnm/Vitamin#1170]
Hi, we've been using the Vitamin starter and everything worked great in the beginning :)

But at some point as the project grew, we occasionally had builds that would break completely with this error:
![Screenshot 2023-02-02 at 22 27 07](https://user-images.githubusercontent.com/3296643/216453330-09724037-c4dc-46eb-8ca0-c6d3ce6959a6.png)

It was quite harder debugging as it only happens once in a while, but more frequently when building through our CI pipeline.
We finally found that disabling these lines used in this starter would stop the errors:

![Screenshot 2023-02-02 at 22 28 12](https://user-images.githubusercontent.com/3296643/216453625-5bd2dc86-7525-487f-8e69-e50d3c5d1313.png)

Not sure if this is only specific to our use case and combination of dependencies, but I wanted to flag it here in case other people had the same problem. I'm also curious why `optimizeDeps` was disabled in the first place?

**Comment by wtchnm** [comment]
Hey @madsnedergaard, sorry for the inconvenience!

This setting was introduced in the migration to Vite v3 and is intended to remove the differences between dev and prod present in v2: https://v3.vitejs.dev/guide/migration.html#using-esbuild-deps-optimization-at-build-time.

As it is causing problems, I will remove this configuration until it is more stable.

Thanks!

**Comment by madsnedergaard** [comment]
> Hey @madsnedergaard, sorry for the inconvenience!
> 
> This setting was introduced in the migration to Vite v3 and is intended to remove the differences between dev and prod present in v2: [v3.vitejs.dev/guide/migration.html#using-esbuild-deps-optimization-at-build-time](https://v3.vitejs.dev/guide/migration.html#using-esbuild-deps-optimization-at-build-time).
> 
> As it is causing problems, I will remove this configuration until it is more stable.
> 
> Thanks!

Ah, thanks for sharing the link and additional context :)
I'm unsure which combination of dependencies in [our stack](https://github.com/electricitymaps/electricitymaps-contrib) caused this, so it might be rare edge case - but probably still nice to play it safe :)
