### ISSUE TITLE
ESLint Parsing Error

### ISSUE THREAD

**Issue by AkisArou** [wtchnm/Vitamin#525]
Hello, first of all thanks for this nice template.

I've just downloaded this template, and I am facing an ESLint issue in the cypress folder files. (src files are correctly linted)
I am using WebStorm as my IDE.
![Screenshot 2021-11-29 173542](https://user-images.githubusercontent.com/47406069/143897553-9a6a8441-df86-4796-a480-0112124cd3ad.png)

**Comment by wtchnm** [comment]
Hello Adam, I'm glad you liked the template!
Can you try again please?

**Comment by AkisArou** [comment]
Seems to be fixed! Thanks for the fast response!

**Comment by wtchnm** [comment]
Nice! You're welcome!
