### ISSUE TITLE
would you guys be willing to add a state management library like Redux

### ISSUE THREAD

**Issue by ZhengjieYe** [wtchnm/Vitamin#715]
Hi, would you guys be willing to add a state management library like Redux?
I'm currently trying to do this, but I'm still new to React, so I don't know what's the best practice to add it...

**Comment by ZhengjieYe** [comment]
That's so kind of you! Thank you!! Yeah, I think Zustand is ok for me.

**Comment by wtchnm** [comment]
Hey @ZhengjieYe, sorry for the big delay.

Unfortunately, I couldn't find a valid reason for adding a state management library to this template.
You can put anything async in react-query and the rest in a Context.
