### ISSUE TITLE
Make `"eslint.packageManager": "pnpm"` in `.vscode/settings.json`? 

### ISSUE THREAD

**Issue by virtuoushub** [wtchnm/Vitamin#984]
https://github.com/wtchnm/Vitamin/blob/0d6270b6fc107e12c25a39a9f8e925f56a147631/.vscode/settings.json#L13

is there a benefit to making this be `pnpm`? 

afaik, it being set to `yarn` is probably benign; but just wanted to call it out in case it helps.

> `eslint.packageManager`: controls the package manager to be used to resolve the ESLint library. This has only an influence if the ESLint library is resolved globally. Valid values are `"npm"` or `"yarn"` or `"pnpm"`.
https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

---

see also:
- https://github.com/wtchnm/Vitamin/commit/3fc261c1249352dafffb80960722847c30970613

**Comment by wtchnm** [comment]
Hey Peter, thanks for noticing this! I think I will remove this setting as it only takes effect when ESLint is resolved globally, which is not the case.
