### ISSUE TITLE
Please update dependencies to latest

### ISSUE THREAD

**Issue by suerta-git** [wtchnm/Vitamin#985]
Hi folks,

This is an awesome template and I am very enjoy it. But I found there are some dependencies which are not the latest ones under this template, and some configuration files are also using legacy settings/formats.

I very much wish I could use the new features brought from latest version of dependencies when I start a new project, so can you guys check and update these things?

For example:

|  Object  | Current | Latest |
| --- | --- | --- |
| React | 17.0.2 | 18.x.x |
| Cypress | 9.7.0 | 10.x.x|
| configuration file for cypress | `cypress.json` (marked as legacy now) | `cypress.config.ts` |
| configurations for vercel | `routes` property (marked as legacy now) | `rewrites` property (recommended now) |
| ... | ... | ... |

**Comment by wtchnm** [comment]
Closed by #804, #990 and #991.
